#!/bin/bash

echo "🌊 Flow Tracer Demo - Track Data Through Your Code!"
echo "=================================================="
echo ""
echo "This is what Claudes have been dreaming of!"
echo ""
echo "1️⃣ Basic Flow Tracing:"
echo "---------------------"
echo "Track how 'config' flows through the codebase:"
echo ""
bun run src/tools/smartgrep/cli.ts flow config | head -50
echo ""
echo "... (truncated for demo)"
echo ""

echo "2️⃣ Property Flow Tracing:"
echo "------------------------"
echo "Track specific properties like 'projectPath':"
echo ""
bun run src/tools/smartgrep/cli.ts flow projectPath | head -30
echo ""

echo "3️⃣ Why This Matters for Claudes:"
echo "--------------------------------"
echo "❓ Question: 'Where does user input end up?'"
echo "✅ Answer: smartgrep flow request.body"
echo ""
echo "❓ Question: 'How does config get to this function?'"
echo "✅ Answer: smartgrep flow config"
echo ""
echo "❓ Question: 'What transforms this data?'"
echo "✅ Answer: The flow shows every step!"
echo ""

echo "🎯 Flow Types Detected:"
echo "----------------------"
echo "📥 INPUT - Where data enters (destructuring, parameters)"
echo "📝 ASSIGNMENT - Where values are assigned"
echo "🔄 PARAMETER - Function parameters"
echo "📞 CALL - Function calls passing data"
echo "📤 RETURN - Where data is returned"
echo "🔍 USAGE - Where data is used"
echo ""

echo "💡 This helps Claudes understand:"
echo "• The complete journey of data"
echo "• What functions touch the data"
echo "• Where transformations happen"
echo "• The actual execution flow"