#!/bin/bash
# Demo script for charm TUIs

echo "🎉 Charm TUI Demo - Phase 2 Complete!"
echo ""
echo "We've successfully created Go-based TUIs with optional --tui flags."
echo ""
echo "Available commands:"
echo ""
echo "1. SmartGrep (Semantic Search):"
echo "   ./build/bin/smartgrep --help           # Show help"
echo "   ./build/bin/smartgrep 'auth'           # CLI mode (fast for Claude)"
echo "   ./build/bin/smartgrep --tui            # Interactive TUI mode"
echo ""
echo "2. Curator (AI Assistant):"
echo "   ./build/bin/curator overview .         # CLI mode"
echo "   ./build/bin/curator --tui              # Interactive TUI mode"
echo "   ./build/bin/curator chat --tui         # Chat with markdown rendering"
echo ""
echo "3. Monitor (Live Dashboard):"
echo "   ./build/bin/monitor status             # CLI mode"
echo "   ./build/bin/monitor --tui              # Interactive dashboard"
echo "   ./build/bin/monitor watch --tui        # Live monitoring"
echo ""
echo "Key features:"
echo "- ✅ CLI mode by default (Claude-optimized)"
echo "- ✅ Optional --tui flag for interactive mode"
echo "- ✅ Beautiful rendering with Charm libraries"
echo "- ✅ Markdown support in Curator"
echo "- ✅ Real-time updates in Monitor"
echo "- ✅ Clean architecture with cmd/internal separation"
echo ""
echo "Try it out:"
echo "  cd charm-tui"
echo "  ./build/bin/smartgrep --tui"